/* eslint-disable no-param-reassign */

import { createSlice } from '@reduxjs/toolkit';
import { addSectionAsync, showList } from '../AllLists/allListsSlice';

const initialState = {
  showAddSectionForm: false,
  someOtherState: null,
};

export const selectedListSlice = createSlice({
  name: 'selectedList',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    increment: (state) => {
      // Redux Toolkit allows us to write "mutating" logic in reducers. It
      // doesn't actually mutate the state because it uses the Immer library,
      // which detects changes to a "draft state" and produces a brand new
      // immutable state based off those changes
      state.value += 1;
    },
    // Use the PayloadAction type to declare the contents of `action.payload`
    setShowAddSectionForm: (state, action) => {
      state.showAddSectionForm = action.payload;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(addSectionAsync.fulfilled, (state) => {
        state.showAddSectionForm = false;
      })
      .addCase(showList, (state) => {
        state.showAddSectionForm = false;
      });
  },
});

export const { increment, setShowAddSectionForm } = selectedListSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectShowAddSectionForm = (state) => state.selectedList.showAddSectionForm;

// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.
export const incrementIfOdd = (amount) => (dispatch, getState) => {
  const currentValue = selectShowAddSectionForm(getState());
  if (currentValue % 2 === 1) {
    dispatch(increment(amount));
  }
};

export default selectedListSlice.reducer;
